[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["benaryorg <binary@benary.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
regex = "^1.4"
lazy_static = "^1.4"
num = "^0.3.1"
clap = "^2.33"

[dependencies.reqwest]
version = "^0.10.9"
default-features = false
features = ["blocking","rustls-tls"]

